// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Visu

#include "../ui.h"

void ui_Dimm_screen_init(void)
{
ui_Dimm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Dimm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DimmValue = lv_arc_create(ui_Dimm);
lv_obj_set_width( ui_DimmValue, 200);
lv_obj_set_height( ui_DimmValue, 200);
lv_obj_set_align( ui_DimmValue, LV_ALIGN_CENTER );

lv_obj_set_style_arc_width(ui_DimmValue, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_DimmLabel = lv_label_create(ui_Dimm);
lv_obj_set_width( ui_DimmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DimmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DimmLabel, 0 );
lv_obj_set_y( ui_DimmLabel, 63 );
lv_obj_set_align( ui_DimmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DimmLabel,"");

ui_DimmLabelValue = lv_label_create(ui_Dimm);
lv_obj_set_width( ui_DimmLabelValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DimmLabelValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DimmLabelValue, 0 );
lv_obj_set_y( ui_DimmLabelValue, 97 );
lv_obj_set_align( ui_DimmLabelValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_DimmLabelValue,"0%");

lv_obj_add_event_cb(ui_DimmValue, ui_event_DimmValue, LV_EVENT_ALL, NULL);

}
